---
config:
  default: true
  line-length: false
  no-hard-tabs: false
  commands-show-output: false

globs:
  - "**/*.{md,markdown}"

ignores:
  - "CHANGELOG.md"
  - "releases/**"
  - "docs/cli/**"
  - "docs/apis/**"
